In [6]:
import numpy as np

In [13]:
#list
from time import process_time
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time - start_time)

0.0


In [14]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array += 5
end_time=process_time()
print(end_time - start_time)

0.0


In [18]:
list1=[1,2,3,5,4]
print(list1)
type(list1)

[1, 2, 3, 5, 4]


list

In [19]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [21]:
a=np.array([1,2,3,4,6])
print(a)

[1 2 3 4 6]


In [24]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)
print(type(b))
print(b.shape)
print(b.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
(2, 4)
2


In [27]:
c=np.array([(1,2,4),(3,5,6),(2,7,9),(3,6,8)],dtype='int')
print(c)
print(c.shape)
print(c.ndim)


[[1 2 4]
 [3 5 6]
 [2 7 9]
 [3 6 8]]
(4, 3)
2


In [30]:
d=np.zeros((3,3),dtype='int')
print(d)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [31]:
e=np.ones((3,3),dtype='int')
print(e)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [33]:
f=np.full((4,5),7)
print(f)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [35]:
g=np.eye((3),dtype='int')
print(g)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [40]:
h=np.random.random((5,4))
print(h)

[[0.84984436 0.08301716 0.74209433 0.13408081]
 [0.46274437 0.73487757 0.50397213 0.46502446]
 [0.75578918 0.19515533 0.55628378 0.54886607]
 [0.80814536 0.64774781 0.20743807 0.54501779]
 [0.41723885 0.1219144  0.18074778 0.26327635]]


In [42]:
i=np.random.randint(10,100,(5,4))
print(i)

[[92 40 37 65]
 [68 10 17 36]
 [64 73 86 82]
 [78 58 37 28]
 [15 64 59 54]]


In [43]:
j=np.linspace(10,100,5)
print(j)

[ 10.   32.5  55.   77.5 100. ]


In [44]:
k=np.arange(10,100,5)
print(k)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [45]:
#to convert a list to numpy
list2=[10,20,30,40,50]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [46]:
l=np.random.randint(10,90,(5,5))
print(l)

[[59 72 21 68 80]
 [67 18 36 83 37]
 [29 44 78 47 66]
 [64 14 80 16 20]
 [81 45 72 60 62]]


In [47]:
print(l.shape)

(5, 5)


In [48]:
print(l.ndim)

2


In [49]:
print(l.size)

25


In [50]:
print(l.dtype)

int32


In [51]:
#Addition in normal list
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [52]:
#addition in numpy
a=np.random.randint(10,20,(2,2))
b=np.random.randint(0,10,(2,2))
print(a)
print(b)

[[18 11]
 [10 17]]
[[5 6]
 [2 6]]


In [53]:
print(a+b)
print(a-b)
print(a/b)
print(a*b)


[[23 17]
 [12 23]]
[[13  5]
 [ 8 11]]
[[3.6        1.83333333]
 [5.         2.83333333]]
[[ 90  66]
 [ 20 102]]


In [54]:
a=np.random.randint(10,20,(3,3))
b=np.random.randint(0,10,(3,3))
print(a)
print(b)

[[19 11 16]
 [17 10 17]
 [11 18 11]]
[[1 7 0]
 [5 2 3]
 [1 0 1]]


In [55]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[20 18 16]
 [22 12 20]
 [12 18 12]]
[[18  4 16]
 [12  8 14]
 [10 18 10]]
[[19 77  0]
 [85 20 51]
 [11  0 11]]
[[19.          1.57142857         inf]
 [ 3.4         5.          5.66666667]
 [11.                 inf 11.        ]]


C:\Users\HP\AppData\Local\Temp\ipykernel_840\785049711.py:4: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(a,b))


In [56]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)
print(array.ndim)

[[9 4 5]
 [1 5 0]]
(2, 3)
2


In [57]:
#transpose of numpy array
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[9 1]
 [4 5]
 [5 0]]
(3, 2)


In [58]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 3 7]
 [1 8 6]]
(2, 3)


In [59]:
trans1=array.T
print(trans1)
print(trans1.shape)

[[3 1]
 [3 8]
 [7 6]]
(3, 2)


In [60]:
#reshaping the array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[5 9 8]
 [6 5 8]]
(2, 3)


In [61]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[5 9]
 [8 6]
 [5 8]]
(3, 2)
